backend:
  name: git-gateway
  branch: feature/netlify-cms # Branch to update (optional; defaults to master)
media_folder: "src/assets/images/uploads"
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
collections:
  - name: "projects"
    label: "Projects"
    folder: "src/assets/data/projects"
    create: false
    delete: false
    editor:
      preview: true
    format: json
    slug: "projects"
    summary: "Projects"
    fields:
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { label: "Client", name: "client", widget: "string" }
          - { label: "Description", name: "description", widget: "string" }