backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "src/assets/images"
collections:
  - name: "content"
    identifier_field: "name"
    label: "Site content"
    folder: "src/assets/data"
    create: false
    delete: true
    editor:
      preview: false
    format: json
    slug: "content"
    summary: "Content for the site"
    fields:
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { name: "heading", widget: "string" }
          - { name: "date", widget: "string" }
          - { name: "status", widget: "string" }
          - { name: "status_colour", widget: "string" }
          - { name: "description", widget: "string" }
          - { name: "link", widget: "string" }
