backend:
  name: git-gateway
  branch: feature/netlify-cms # Branch to update (optional; defaults to master)
media_folder: "src/assets/images"
collections:
  - name: "projects"
    identifier_field: "name"
    label: "Projects"
    folder: "src/assets/data"
    create: true
    delete: false
    editor:
      preview: false
    format: json
    slug: "projects"
    summary: "Projects"
    fields:
      - label: "Projects"
        name: "projects"
        widget: "list"
        fields:
          - { name: "date", widget: "string" }
          - { name: "status", widget: "string" }
          - { name: "status_colour", widget: "string" }
          - { name: "heading", widget: "string" }
          - { name: "description", widget: "string" }
          - { name: "location", widget: "string" }